# Use following keys for type  #
#   bool    = 2                #
#   int     = 3                #
#   float   = 4                #
#   string  = 5                #

- key: model_filename
  type: 5
  value: path/to/mobilenet.tflite
