# Use following keys for type  #
#   bool    = 2                #
#   int     = 3                #
#   float   = 4                #
#   string  = 5                #

- key: model_filename
  type: 5
  value: /home/root/mobilenetv2_035_unet.tflite
- key: class_index
  type: 3
  value: 9 # lass 9 is sea
